REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 5011, 'Crossbows');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 674, 'Dual Wield');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 264, 'Bow');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 1024, 24866, 'Cat Faster');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 1180, 'Daggers');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 201, 'One-Handed Swords');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 198, 'One-Handed Maces');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 196, 'One-Handed Axesäxte');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 15590, 'Fist Weapons');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 668, 'Language: Common');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 8737, 'Mail');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 9077, 'Leather');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 669, 'Language: Orcish');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 4, 883, 'Pet Call');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 4, 2641, 'Pet Free');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 4, 982, 'Pet Rezz');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 4, 1515, 'Pet Tame');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 33391, 'Pet Command');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 750, 'Plate Mail');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 9116, 'Shield');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 266, 'Guns');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 200, 'Polearms');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 9078, 'Cloth');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 227, 'Staves');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 46917, 'Titan\'s Grip');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 203, 'Unarmed');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 5009, 'Wands');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 202, 'Two-Handed Swords');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 199, 'Two-Handed Maces');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 197, 'Two-Handed Axes');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 33388, 'Apprentice Riding');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 818, 'Cooking Fire');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (2097152, 0, 68996, 'Worgen Two Forms');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 119467, 'Battle Pet Training');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 33391, 'Journeyman Riding');
REPLACE INTO `playercreateinfo_spell_custom` VALUES (0, 0, 260172, 'CUSTOM: Beta Mount');

TRUNCATE player_factionchange_achievement;
TRUNCATE player_factionchange_items;
TRUNCATE player_factionchange_quests;
TRUNCATE player_factionchange_reputations;
TRUNCATE player_factionchange_spells;
TRUNCATE player_factionchange_titles;
TRUNCATE player_factionchange_items;