REPLACE INTO `command` (`name`, `permission`, `help`) VALUES ('mountsystem create byMountId', 2102, 'Syntax: .mountsystem create byMountId\n\nCreates a mount using the MountId.');
REPLACE INTO `command` (`name`, `permission`, `help`) VALUES ('mountsystem create bySpellId', 2102, 'Syntax: .mountsystem create bySpellId\n\nCreates a mount using the SpellId.');
REPLACE INTO `command` (`name`, `permission`, `help`) VALUES ('mountsystem info', 2103, 'Syntax: .mountsystem info\n\nGives information about the Mount');
REPLACE INTO `command` (`name`, `permission`, `help`) VALUES ('reload mountsystem', 2101, 'Syntax: .reload mountsystem\n\nReloads all mounts from the database.\nATTENTION: All players will be kicked off their mounts!');

REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50504, 'Mount Id: %u\nCharacter Mount Id: %u\nName: %s (%s)\nOwner: %s\n\nFuel: %f/%f\nCondition: %f/%f\nDirt: %f/100', NULL, NULL, 'Mount Id: %u\nCharakter Mount Id: %u\nName: %s (%s)\nBesitzer: %s\n\nEnergie: %f/%f\nVerfassung: %f/%f\nSchmutz: %f/100', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50503, 'The selected target is a mount!', NULL, NULL, 'Das ausgewählte Ziel ist ein Reittier!', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50502, 'Mount successfully created!', NULL, NULL, 'Reittier erfolgreich erstellt!', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50501, 'A mount could be found for the ID, but no mount system template was created for this mount!', NULL, NULL, 'Es konnte ein Reittier zu der Id gefunden werden, jedoch wurde für dieses Reittier kein Reittier System Template angelegt!', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50500, 'No mount could be found for the id in WoW', NULL, NULL, 'Zu der Id konnte kein Reittier in WoW gefunden werden', NULL, NULL, NULL, NULL, NULL);
