REPLACE INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `name`, `femaleName`, `subname`, `TitleAlt`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `HealthScalingExpansion`, `RequiredExpansion`, `VignetteID`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `dmgschool`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `unit_flags3`, `dynamicflags`, `family`, `trainer_class`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `HealthModifier`, `HealthModifierExtra`, `ManaModifier`, `ManaModifierExtra`, `ArmorModifier`, `DamageModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `WidgetSetID`, `WidgetSetUnitConditionID`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES (1050000, 0, 0, 0, 0, 0, 'Mount', '', NULL, NULL, NULL, 30000, 60, 60, 0, 0, 0, 35, 1, 1, 1.14286, 1, 0, 0, 0, 0, 1, 1, 8, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 800000, 800001, 800002, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 3, 1, 1, 1, 1, 1, 1, 1, 1, 0, 140, 0, 0, 1, 0, 2, 'npc_mountsystem_mount', -1);
REPLACE INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `visibilityDistanceType`, `auras`) VALUES (1050000, 0, 0, 0, 1, 0, 0, 0, 0, 0, '');
REPLACE INTO `creature_template_locale` (`entry`, `locale`, `Name`, `NameAlt`, `Title`, `TitleAlt`, `VerifiedBuild`) VALUES (1050000, 'deDE', 'Reittier', '', '', NULL, -1);
REPLACE INTO `creature_template_model` (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`, `VerifiedBuild`) VALUES (1050000, 0, 2405, 1, 1, -1);

REPLACE INTO `gameobject_template` VALUES (1003073, 5, 10167, 'Improved trough (Mount System)', '', '', '', 0.5, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 'go_mountsystem_trough', -1, '2021-09-24 22:11:06');
REPLACE INTO `gameobject_template` VALUES (1003072, 5, 10167, 'Trough (Mount System)', '', '', '', 0.5, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 'go_mountsystem_trough', -1, '2021-09-24 22:11:07');
REPLACE INTO `gameobject_template` VALUES (1003071, 5, 10167, 'Simple trough (Mount System)', '', '', '', 0.5, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 'go_mountsystem_trough', -1, '2021-09-24 22:11:08');
REPLACE INTO `gameobject_template_locale` VALUES (1003073, 'deDE', 'Verbesserter Trog (Reittier System)', '', NULL, -1);
REPLACE INTO `gameobject_template_locale` VALUES (1003072, 'deDE', 'Trog (Reittier System)', '', NULL, -1);
REPLACE INTO `gameobject_template_locale` VALUES (1003071, 'deDE', 'Einfacher Trog (Reittier System)', '', NULL, -1);

REPLACE INTO `gossip_menu_option` (`MenuId`, `OptionIndex`, `OptionIcon`, `OptionText`, `OptionBroadcastTextId`, `OptionType`, `OptionNpcFlag`, `VerifiedBuild`) VALUES (30000, 0, 0, 'Grooming / Polishing', 0, 0, 0, -1);
REPLACE INTO `gossip_menu_option` (`MenuId`, `OptionIndex`, `OptionIcon`, `OptionText`, `OptionBroadcastTextId`, `OptionType`, `OptionNpcFlag`, `VerifiedBuild`) VALUES (30000, 8, 0, 'Create parking ticket', 0, 0, 0, -1);
REPLACE INTO `gossip_menu_option` (`MenuId`, `OptionIndex`, `OptionIcon`, `OptionText`, `OptionBroadcastTextId`, `OptionType`, `OptionNpcFlag`, `VerifiedBuild`) VALUES (30000, 9, 0, 'Pay parking ticket', 0, 0, 0, -1);

REPLACE INTO `gossip_menu_option_box` (`MenuId`, `OptionIndex`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextId`) VALUES (30000, 3, 0, 50, 'Are you sure you want to send the mount back to the stable?\n\nThis action costs reward coins', 0);
REPLACE INTO `gossip_menu_option_box` (`MenuId`, `OptionIndex`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextId`) VALUES (30000, 8, 0, 0, 'Are you sure you want to give this mount a parking ticket?', 0);
REPLACE INTO `gossip_menu_option_box` (`MenuId`, `OptionIndex`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextId`) VALUES (30000, 9, 0, 200, 'You have received a ticket for parking your mount in contravention of the rules. \n\nThis costs reward coins', 0);

REPLACE INTO `gossip_menu_option_locale` (`MenuId`, `OptionIndex`, `Locale`, `OptionText`, `BoxText`) VALUES (30000, 3, 'deDE', 'Zurück in den Stall schicken', 'Sind Sie sicher, dass Sie das Reittier zum Stall zurückschicken möchten?\n\nDiese Aktion kostet Belohnungsmünzen');
REPLACE INTO `gossip_menu_option_locale` (`MenuId`, `OptionIndex`, `Locale`, `OptionText`, `BoxText`) VALUES (30000, 8, 'deDE', 'Strafzettel austellen', 'Bist du dir sicher, dass du Diesem Reittier ein Strafzettel erteilen möchtest?');
REPLACE INTO `gossip_menu_option_locale` (`MenuId`, `OptionIndex`, `Locale`, `OptionText`, `BoxText`) VALUES (30000, 9, 'deDE', 'Strafzettel bezahlen', 'Du hast ein Strafzettel für das Regelwedrige Abstellen deines Reittiers erhalten. \n\nDieser kostet Belohnungsmünzen');

REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50300, 'There is no longer a seat available on this mount.', NULL, NULL, 'Es ist kein Sitz auf diesem Reittier mehr verfügbar.', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50301, 'You must be in the same group to be able to enter.', NULL, NULL, 'Ihr müsst in der selben Gruppe sein um Einsteigen zu können.', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50302, '|cff1aff1aHappy|r', NULL, NULL, '|cff1aff1aGlücklich|r', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50303, '|cff75d3ffEnergetic|r', NULL, NULL, '|cff75d3ffEnergiegeladen|r', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50304, '|cfffdfdfdNormal|r', NULL, NULL, '|cfffdfdfdNormal|r', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50305, '|cfffa8714Underwhelmed|r', NULL, NULL, '|cfffa8714Unterfordert|r', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50306, '|cffff2600Neglected|r', NULL, NULL, '|cffff2600Vernachlässigt|r', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50307, '|cff1aff1aClean|r', NULL, NULL, '|cff1aff1aSauber|r', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50308, '|cfff7ff1aLittle Dirty|r', NULL, NULL, '|cfff7ff1aLeicht verschmutzt|r', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50309, '|cfffa8714Dirty|r', NULL, NULL, '|cfffa8714Verschmutzt|r', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50310, '|cffff2600Neglected|r', NULL, NULL, '|cffff2600Verwahrlost|r', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50311, 'The %s character can now use the %s mount.', NULL, NULL, 'Der Charakter %s kann nun das Reittier %s benutzen.', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50312, 'The character name "%s" could not be found.', NULL, NULL, 'Der Charaktername "%s" konnte nicht gefunden werden.', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50313, 'The %s character can no longer use the %s mount.', NULL, NULL, 'Der Charakter %s kann das Reittier %s nicht mehr benutzen.', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50314, 'The name "%s" you selected is invalid.', NULL, NULL, 'Der von dir Ausgewählte Name "%s" ist ungültig.', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50315, 'Your mount has run out of energy or is in too bad a condition for you to mount.', NULL, NULL, 'Dein Reittier hat keine Energie mehr oder ist in einer zu schlechten Verfassung, weshalb du nicht auftseigen kannst.', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50316, 'This mount has no owner. Inform a supporter to delete it.', NULL, NULL, 'Dieses Reittier hat keinen Besitzer. Informiere einen Unterstützer um es zu löschen.', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50317, 'You have no rights to use this mount.', NULL, NULL, 'Du hast keine Rechte dieses Reittier zu benutzen.', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50318, '%s rears up and throws you down, good and proper.', NULL, NULL, '%s bäumt sich auf und wirft euch samt hab und gut herunter.', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50319, '%s is dirty from top to bottom...disgusting!', NULL, NULL, '%s ist von oben bis unten dreckig...ekelhaft!', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50320, '%s leaves something behind. Maybe you should pick it up.', NULL, NULL, '%s hinterlässt etwas hinter sich. Vielleicht solltet Ihr es aufheben.', NULL, NULL, NULL, NULL, NULL);

