DELETE FROM `gossip_menu` WHERE MenuID = 30000;
DELETE FROM `gossip_menu_option` WHERE MenuID = 30000;
DELETE FROM `gossip_menu_option_locale` WHERE MenuID = 30000;

REPLACE INTO `gossip_menu` (`MenuID`, `TextID`, `VerifiedBuild`) VALUES (300000, 0, -1);
UPDATE `creature_template` SET `gossip_menu_id`='300000' WHERE `entry`=1050000;

REPLACE INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `Language`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES (300000, 9, 0, 'Pay parking ticket', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, -1);
REPLACE INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `Language`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES (300000, 8, 0, 'Create parking ticket', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, -1);
REPLACE INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `Language`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES (300000, 7, 0, 'Rename', 0, 0, 0, 0, 0, 0, 1, 0, NULL, 0, -1);
REPLACE INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `Language`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES (300000, 6, 0, 'Remove Rights', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, -1);
REPLACE INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `Language`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES (300000, 5, 0, 'Add Rights', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, -1);
REPLACE INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `Language`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES (300000, 4, 0, 'Set location as stable', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, -1);
REPLACE INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `Language`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES (300000, 3, 0, 'Send back to the stable', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, -1);
REPLACE INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `Language`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES (300000, 2, 0, 'Mount', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, -1);
REPLACE INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `Language`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES (300000, 1, 0, 'Let follow', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, -1);
REPLACE INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `Language`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES (300000, 0, 0, 'Grooming / Polishing', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, -1);

REPLACE INTO `gossip_menu_option_locale` (`MenuID`, `OptionID`, `Locale`, `OptionText`, `BoxText`) VALUES (300000, 0, 'deDE', 'Striegeln / Polieren', NULL);
REPLACE INTO `gossip_menu_option_locale` (`MenuID`, `OptionID`, `Locale`, `OptionText`, `BoxText`) VALUES (300000, 1, 'deDE', 'Folgen lassen', NULL);
REPLACE INTO `gossip_menu_option_locale` (`MenuID`, `OptionID`, `Locale`, `OptionText`, `BoxText`) VALUES (300000, 2, 'deDE', 'Aufsteigen', NULL);
REPLACE INTO `gossip_menu_option_locale` (`MenuID`, `OptionID`, `Locale`, `OptionText`, `BoxText`) VALUES (300000, 3, 'deDE', 'Zurück in den Stall schicken', 'Sind Sie sicher, dass Sie das Reittier zum Stall zurückschicken möchten?\n\nDiese Aktion kostet Belohnungsmünzen');
REPLACE INTO `gossip_menu_option_locale` (`MenuID`, `OptionID`, `Locale`, `OptionText`, `BoxText`) VALUES (300000, 4, 'deDE', 'Standort als Stall festlegen', 'Sind Sie sich Sicher, dass Sie diesen Standort als Stall festlegen wollen?');
REPLACE INTO `gossip_menu_option_locale` (`MenuID`, `OptionID`, `Locale`, `OptionText`, `BoxText`) VALUES (300000, 5, 'deDE', 'Rechte vergeben', 'Gib den Namen des Charakters ein, der Rechte für dein Reittier erhalten soll:');
REPLACE INTO `gossip_menu_option_locale` (`MenuID`, `OptionID`, `Locale`, `OptionText`, `BoxText`) VALUES (300000, 6, 'deDE', 'Rechte nehmen', 'Gib den Namen des Charakters ein, der keine Rechte mehr für dein Reittier haben soll:');
REPLACE INTO `gossip_menu_option_locale` (`MenuID`, `OptionID`, `Locale`, `OptionText`, `BoxText`) VALUES (300000, 7, 'deDE', 'Umbenennen', 'Gebt einen Namen für Euren Reittier ein:');
REPLACE INTO `gossip_menu_option_locale` (`MenuID`, `OptionID`, `Locale`, `OptionText`, `BoxText`) VALUES (300000, 8, 'deDE', 'Strafzettel austellen', 'Bist du dir sicher, dass du Diesem Reittier ein Strafzettel erteilen möchtest?');
REPLACE INTO `gossip_menu_option_locale` (`MenuID`, `OptionID`, `Locale`, `OptionText`, `BoxText`) VALUES (300000, 9, 'deDE', 'Strafzettel bezahlen', 'Du hast ein Strafzettel für das Regelwedrige Abstellen deines Reittiers erhalten. \n\nDieser kostet Belohnungsmünzen');
