REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (800006, 'spell_housing_hearthstone');

REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50067, 'This place has been set as your home.', NULL, NULL, 'Dieser Ort wurde als dein Heimatort festgelegt.', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50066, 'You cannot set this location as your home location because you do not have access rights.', NULL, NULL, 'Du kannst diesen Ort nicht als dein Heimatort festlegen, da du keine Zugangsrechte hast.', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50065, 'You cannot set this place as your home.', NULL, NULL, 'Du kannst diesen Ort nicht als Heimatort festlegen.', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES (50064, 'You have not yet chosen a home for your house hearthstone.', NULL, NULL, 'Du hast bisher kein Heimatort für dein Haus Ruhestein gewählt.', NULL, NULL, NULL, NULL, NULL);

SET foreign_key_checks = 0;
REPLACE INTO `battlepay_product_group` (`GroupID`, `Name`, `IconFileDataID`, `DisplayType`, `Ordering`) VALUES (4, 'Hearthstone', 134414, 0, 40);
REPLACE INTO `battlepay_product_group_locales` (`GroupID`, `Locale`, `Name`) VALUES (4, 'deDE', 'Ruhestein');
REPLACE INTO `battlepay_display_info` (`DisplayInfoId`, `CreatureDisplayInfoID`, `FileDataID`, `UiTextureAltlasId`, `DisplayCardWidth`, `Name1`, `Name2`, `Name3`, `Name4`, `Name5`, `Flags`) VALUES (15, 0, 1041860, 0, 4, 'Housing Hearthstone', '', 'The "Home Hearthstone" – your swift way back home! With a 5-minute cooldown, you can teleport directly to your own four walls from any location.|n|nYou can customize your home location as you wish, provided that you are in a residential or business area for which you have access permission.', '', '', 128);
REPLACE INTO `battlepay_display_info_locales` (`Id`, `Locale`, `Name1`, `Name2`, `Name3`, `Name4`, `Name5`) VALUES (15, 'deDE', 'Haus Ruhestein', '', 'Der "Haus Ruhestein" – deine schnelle Rückkehrmöglichkeit nach Hause! Mit einer 5-minütigen Abklingzeit kannst du dich von jedem Ort direkt in deine eigenen vier Wände teleportieren.|n|nDu kannst deinen Heimatort nach Belieben festlegen, vorausgesetzt, du befindest dich in einem Wohn- oder Geschäftsbereich, für den du eine Zugangsberechtigung hast.\r\n', '', '');
REPLACE INTO `battlepay_product` (`ProductID`, `NormalPriceFixedPoint`, `CurrentPriceFixedPoint`, `Type`, `WebsiteType`, `CustomValue`, `ChoiceType`, `Flags`, `DisplayInfoID`, `SpellID`, `CreatureID`, `ClassMask`, `ScriptName`) VALUES (15, 20000, 20000, 0, 3, 0, 2, 0, 15, 0, 0, 0, '');
REPLACE INTO `battlepay_product_item` (`ID`, `ProductID`, `ItemID`, `Quantity`, `DisplayID`, `PetResult`, `IgnoreOwnCheck`) VALUES (7, 15, 500017, 1, 15, 0, 1);
REPLACE INTO `battlepay_shop_entry` (`EntryID`, `GroupID`, `ProductID`, `Ordering`, `VasServiceType`, `StoreDeliveryType`, `DisplayInfoID`) VALUES (15, 4, 15, 1, 1, 2, 0);
SET foreign_key_checks = 1;